# -*- coding: utf-8 -*-
"""Introduction to forecasting Philippine stock prices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xBwyVvX29YLW5v_RhtzImkqW6U9eIxJD
"""

!pip install pandas
!pip install datetime
!pip install fbprophet

import pandas as pd

jfc = pd.read_csv('jfc_20130901_to_20190426.csv')
jfc['CHART_DATE'] = pd.to_datetime(jfc.CHART_DATE)

jfc.tail()

jfc.set_index('CHART_DATE').CLOSE.plot(figsize=(15, 10))
plt.title('Jollibee Daily Closing Price', fontsize=25)

from fbprophet import Prophet
#Forecasting closing prices
ts = jfc[['CHART_DATE', 'CLOSE']]
ts.columns = ['ds', 'y']
ts.head()

m = Prophet(daily_seasonality=True, yearly_seasonality=True).fit(ts)
future = m.make_future_dataframe(periods=7*4*12, freq='D')

pred = m.predict(future)

from matplotlib import pyplot as plt
fig1 = m.plot(pred)
plt.title('Jollibee: Forecasted Daily Closing Price', fontsize=25)

#Plotting returns of JFC
ts_pct = ts.set_index('ds').pct_change()
ts_pct.plot()

#Plotting log returns of JFC
import numpy as np

ts_pct = np.log(ts.set_index('ds').pct_change() + 1)
ts_pct.plot()

ts_pct.hist(bins=50)

m = Prophet(daily_seasonality=True, yearly_seasonality=True).fit(ts_pct.reset_index())
future = m.make_future_dataframe(periods=7*4*12, freq='D')

pred = m.predict(future)

from matplotlib import pyplot as plt
fig1 = m.plot(pred)
plt.title('Jollibee: Forecasted Daily Returns', fontsize=25)

#log first difference of JFC
import numpy as np

ts_pct = np.log(ts.set_index('ds')).diff()
ts_pct.plot()

ts_pct.hist(bins=50)

m = Prophet(daily_seasonality=True, yearly_seasonality=True).fit(ts_pct.reset_index())
future = m.make_future_dataframe(periods=7*4*12, freq='D')
pred = m.predict(future)

from matplotlib import pyplot as plt
fig1 = m.plot(pred)
plt.title('Jollibee: Forecasted Daily Returns', fontsize=25)

